# Chapter 5: A place for everything
#
# A small template for starting an R project. Keep the sections in this order
# so a fresh R session can find the project, its inputs, and its outputs.

# ---- Ready the tools ----
# If needed, install once:
# install.packages("fs")
library(fs)

# ---- Locate the headquarters ----
# This is the only path to change if the project moves to another computer.
setwd(
    path(path_home(), "DataSharp", "enter-the-mind", "running")
)

# ---- Describe the project ----
dir_inputs  <- path("_inputs")
dir_outputs <- path("_outputs")
dir_scripts <- path("_scripts")
dir_temp    <- path("_temp")

dir_out_figures  <- path(dir_outputs, "figs")
dir_out_datasets <- path(dir_outputs, "data")

# Create folders for material generated by the project. Keep original data in
# _inputs and add any input-file paths below when the analysis needs them.
dir_create(c(
    dir_outputs,
    dir_scripts,
    dir_temp,
    dir_out_figures,
    dir_out_datasets
))

# ---- Define inputs and outputs ----
# Add named path() objects here as the analysis grows. For example, keep input
# paths under dir_inputs and generated files under dir_out_figures or
# dir_out_datasets.

# ---- Run the analysis ----
# Add the data import, transformation, figures, and saved outputs here.

# ---- Close open connections ----
# Close any database or other external connections opened by the analysis.
